"""Add play_count to games table

Revision ID: 2ef6aed0a85d
Revises: 768efbaf4137
Create Date: 2025-09-01 19:02:39.911486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef6aed0a85d'
down_revision: Union[str, None] = '768efbaf4137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('play_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'play_count')
    # ### end Alembic commands ###
