"""Add play_count to ContentGame table

Revision ID: 435cadbb764c
Revises: c96ec2edf7da
Create Date: 2025-09-03 20:13:02.597390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '435cadbb764c'
down_revision: Union[str, None] = 'c96ec2edf7da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_games', sa.Column('play_count', sa.Integer(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE content_games SET play_count = 0 WHERE play_count IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_games', 'play_count')
    # ### end Alembic commands ###
