"""add_thumbnail_to_games_table

Revision ID: 7d7aef42cd29
Revises: 4a2e4ce20ff3
Create Date: 2025-09-09 15:56:44.822614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d7aef42cd29'
down_revision: Union[str, None] = '4a2e4ce20ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('thumbnail', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'thumbnail')
    # ### end Alembic commands ###
