"""Add is_published flag to games and GameScore table

Revision ID: c96ec2edf7da
Revises: 2ef6aed0a85d
Create Date: 2025-09-03 19:45:05.691630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c96ec2edf7da'
down_revision: Union[str, None] = '2ef6aed0a85d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('games', sa.Column('is_published', sa.Boolean(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE games SET is_published = false WHERE is_published IS NULL")
    op.execute("UPDATE games SET play_count = 0 WHERE play_count IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'is_published')
    op.drop_table('game_scores')
    # ### end Alembic commands ###
